### ISSUE TITLE
Feature Request: plug-in mechanism in “deployment”

### ISSUE THREAD

**Issue by ShotaKitazawa** [pipe-cd/pipecd#1088]
**What would you like to be added**:

plug-in mechanism in “deployment”

**Why is this needed**:

Now, PipeCD support bellow "deployment".

- Kubernetes
- Terraform
- CloudRun
- Lambda

I look that process of import these executors are hard coded.

- https://github.com/pipe-cd/pipe/blob/402a983c0be10d6fc84c9114a6aa1202663971f6/pkg/app/piped/executor/registry/registry.go#L96-L105

I hope plug-in mechanism in “deployment”. Then, PipeCD will support many "deployment" by various people.

**Comment by nghialv** [comment]
@ShotaKitazawa Thank you for raising the issue. We will add it to the roadmap.
