### ISSUE TITLE
Building a playground place for users to explore WebUI of PipeCD

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipecd#1617]
**What would you like to be added**:

It would be nice if anyone could have a quick look at PipeCD through a demo/playground page.

e.g.
https://playground.pipecd.dev
https://demo.pipecd.dev

Because of security concerns, the playground page will not allow sending the data from external pipeds.
As a first step, we can provide a read-only page with our mock data.

**Why is this needed**:

**Comment by khanhtc1202** [comment]
https://play.pipecd.dev is available 👍
