### ISSUE TITLE
Simplify the build system

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipecd#1634]
**What would you like to be added**:

Currently, we are using Bazel as our unified build system.
Bazel works well, it helps us to archive fast and reproducible builds.
With Bazel, we don't have to install so many tools to build all things for our mono-repo, just one tool for all (backend sources, frontend sources, proto generations, docker image building, pushing...). And with Bazel, our CI and local development workflow become quite simple.

But Bazel also brings some disadvantages, the most one maybe its learning curve; it is hard for our new members, new contributors.

Because PipeCD was released as an OSS, it is time to welcome more new contributors to our project, so I just raised this issue to do more investigation around this topic.

**Why is this needed**:

**Comment by nakabonne** [comment]
Thank you for opening this issue. I've been thinking about we need the opportunity to carefully consider its upside and downside.

**Comment by nakabonne** [comment]
You guys might have already known though. FYI:
- https://github.com/kubernetes/kubernetes/pull/99561
- https://github.com/kubernetes/enhancements/issues/2420

**Comment by nghialv** [comment]
This was already resolved.
