### ISSUE TITLE
Find a better way to help users have a quick list of their applications

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipecd#1669]
**What would you like to be added**:

For big projects, the application number increases very rapidly.
And when that number becomes big enough, finding applications the user really cares about becomes difficult.
So it would be nice if we provide some ways to help our users quickly have the list of their wanted applications.

Actually, recently we have just added the ability to filter an application by its name https://github.com/pipe-cd/pipe/pull/1656, but that is only helpful for the case of finding a single application.
For the list, some options as below can be considered:
- allow the users to label the application and they can filter by the label
- allow each user to PIN application, and the list of PINed application for each user will be shown at the top of the page

**Why is this needed**:

**Comment by khanhtc1202** [comment]
Currently, filter applications by labels is supported at beta status 👍
