### ISSUE TITLE
Force gateway to reload when envoy configuration changed

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipecd#1826]
**What would you like to be added**:

Currently, the old gateway pods keep running even when the envoy configuration was updated.
It is because the pod template of gateway deployment was not changed.
So in order to ensure that the new envoy configuration is loaded and used, we have to force the gateway to reload by adding a hash value of the envoy configuration into the pod template.

**Why is this needed**:

**Comment by nakabonne** [comment]
Another way is using the [hot restart](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/hot_restart) feature by making an xds server ourselves. But it's preferable to restart pods by PipeCD.
