### ISSUE TITLE
Production Hardening: Add doc to show best practices for doing data backup and restore

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipecd#2394]
**What would you like to be added**:

**Why is this needed**:

**Comment by kentakozuka** [comment]
A blog entry was added.
https://pipecd.dev/blog/2023/02/07/pipecd-best-practice-02-control-plane-on-ecs/

**Comment by khanhtc1202** [comment]
@kentakozuka Sorry but I think this issue is about docs for data backup and restore, not operating controlplane, isn't it?

**Comment by kentakozuka** [comment]
oh yea. you are right. reopening 👍 Thanks!
