### ISSUE TITLE
Project recovery & Static admin recovery

### ISSUE THREAD

**Issue by alexander-bruun** [pipe-cd/pipecd#2408]
**What would you like to be added**:
I would like there to be a way to recover a Static Admin account since if you somehow lost it (if you clear cookies without noting it down) you will have to delete the project it self, which is also not possible since there is no project delete feature in the ops http ui.

**Why is this needed**:
To be able to recover a project where the static admin creds have been lost.

**Comment by ffjlabo** [comment]
This prblem will progress on #4844
