### ISSUE TITLE
Piped is not checking StatefultSet while determining deployment strategy for Kubernetes application

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipecd#2456]
**What would you like to be added**:

https://github.com/pipe-cd/pipe/blob/master/pkg/app/piped/planner/kubernetes/kubernetes.go#L306

**Why is this needed**:

It could cause a wrong deployment strategy for the application that is containing StatefulSet resource.

**Comment by Hosshii** [comment]
This is already resolved
/close
