### ISSUE TITLE
Deployment chain - allow rolling out to multiple clusters gradually or promoting across environments

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipecd#2540]
Epic description
---

Currently, one application can be used to deploy a group of resources to a single target provider.
This feature adds the ability to combine multiple applications into a chain/flow.
Users can use it to roll out a group of applications into multiple clusters gradually or promote across environments.

**Comment by khanhtc1202** [comment]
should be safe to close since the deployment chain released under alpha status already.
/close
