### ISSUE TITLE
[ja] In Japanese, the item disappears from the menu.

### ISSUE THREAD

**Issue by riita10069** [pipe-cd/pipecd#2780]
**What happened**:
Items that are not yet in Japanese are not displayed in the menu.
![image](https://user-images.githubusercontent.com/42636694/141652373-fd7a65d4-5d37-4bce-acd7-246b6dc5d182.png)

**What you expected to happen**:
I would like the menu to show the items, even if it is still in English.
I am a native Japanese speaker, so I was investigating the document in Japanese. I found the document to have very few items. However, this is not the case. In fact, they were just not displayed. So I felt that a link to the original document should be posted for the untranslated ones.

**How to reproduce it**:
Please access here.
https://pipecd.dev/ja/docs/user-guide/

**Environment**:
Mac Book Pro arm64
Google Chrome

**Comment by khanhtc1202** [comment]
Hi @riita10069 , all Japanese docs are currently placed under [ja/docs](https://github.com/pipe-cd/pipe/tree/master/docs/content/ja/docs) directly, and we have not translated all of PipeCD docs to Japanese yet.
About the docs in Japanese, we don't have many resources for that in the meantime, but we are happy to accept your help.

**Comment by khanhtc1202** [comment]
![Screen Shot 2021-11-15 at 17 20 08](https://user-images.githubusercontent.com/32532742/141746710-076145fd-2070-46a9-b3ab-125339c4d357.png)
We already have link and note that mention English docs on the top page of Japanese docs. Do you mean to add that note to every single Japanese page?

**Comment by khanhtc1202** [comment]
Staled, and we only support English docs for now 🙏
