### ISSUE TITLE
Update pipectl version to the latest that plan-prevew uses

### ISSUE THREAD

**Issue by kentakozuka** [pipe-cd/pipecd#2818]
**Why is this needed**:

The new command flags are missing.

https://github.com/pipe-cd/pipe/blob/6b6bf58bb08440e44d55609e35d74a98710da133/dockers/actions-plan-preview/Dockerfile#L5

**Comment by t-kikuc** [comment]
Probably this is already fixed.
The new one:
https://github.com/pipe-cd/pipecd/blob/2f57e0ab1d314871ff2c88d7eac3dc9299bb509c/tool/actions-plan-preview/Dockerfile#L8
