### ISSUE TITLE
Eliminate the Environment concept from code to the docs

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipecd#2915]
**What would you like to be added**:
Because we settled on identifying applications by Labels (https://github.com/pipe-cd/pipe/issues/2750), Environment will get unneeded at all. Originally we were looking to promote Deployment using this concept, but [the deployment chain](https://github.com/pipe-cd/pipe/blob/master/docs/rfcs/0007-deployment-chain.md) will be available soon.

Currently it's required at a lot of places so we need to eliminate them in bulk.

**Why is this needed**:

**Comment by nakabonne** [comment]
Related: https://github.com/pipe-cd/pipe/issues/2813

**Comment by nakabonne** [comment]
This should be addressed after the ACL feature gets supported.

**Comment by nghialv** [comment]
> This should be addressed after the ACL feature gets supported.

Any reason for this?
It would be nice if we could have that before the ACL feature is fully implemented.

**Comment by nakabonne** [comment]
@nghialv Currently, all Pipeds must belong to at least one environment and can only deploy to that environment.
So I was concerned that if the newly created application does not belong to any environment, it cannot be deployed with the existing Piepd.

However, if you think about it, it work fine if we made a change that applications that don't belong to any environment can be deployed to any Piped.

**Comment by nghialv** [comment]
> However, if you think about it, it work fine if we made a change that applications that don't belong to any environment can be deployed with any Piped.

Yes, the environment will be eliminated eventually so I think that is fine to make all the `environment` things to be optional.
One vote from me to put this issue at a higher priority to be done first.
Can you investigate all the risks and start solving this issue?

**Comment by nakabonne** [comment]
Alright!

**Comment by nakabonne** [comment]
I would love to include it in the next release which contains the add app from Git feature if possible.

**Comment by nghialv** [comment]
Yes. I hope so too.

**Comment by nakabonne** [comment]
I assumed that if Piped tried to deploy to a different environment, some validation would cause the deployment to fail, but it' was wrong. It limits just the Piped options by the environment when registering an application from the Web UI. So either way, adding app from GIt along with Environment will face this issue.

It turned out that we have to address this as soon as possible, at the same time, we didn't depend on Env than I thought ;)

**Comment by nghialv** [comment]
Close this since it has been split into smaller ones.
/close
