### ISSUE TITLE
Improve plan-preview message for Kubernetes application

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipecd#2982]
**What would you like to be added**:

PlanPreview determines and shows the list of manifests that should be added, deleted, updated once the PR got merged.
But actually, no one will be deleted if the `prune` field of the application is being disabled.
So PlanPreview should take care of that edge case for a better message.

https://pipecd.dev/docs/user-guide/plan-preview/

**Why is this needed**:

**Comment by ffjlabo** [comment]
We will create the enhanced issue for plan preview feature later.
