### ISSUE TITLE
Generate Go module, JSON schema, or Typescript interfaces for Config structs

### ISSUE THREAD

**Issue by yliu-d** [pipe-cd/pipecd#3115]
**What would you like to be added**: When configuring pipecd using some IaC tools such as pulumi, we can define pipecd configuration as objects in real programming languages like Typescript/Golang, but those Config structs under `pkg/config`/`pkg/model` are not exposed as a separate go module. I tried to depend on the entire pipecd module, then found the protobuf generated go files are not checked in to the repo. It would be great if we can generate a separate go module, containing those Config structs, including protobuf generated go files. Then based on that go module we can use other tools to generate JSON schema or Typescript interfaces from Golang structs.

**Why is this needed**: It allows type safety when you are configuring pipecd using IaC tools.

**Comment by nghialv** [comment]
@yliu-d Hi, thank you for your issue.
Could you list all the packages you want to have?

Tbh, we are thinking about adding an automation CI job that generates all essential packages and then pushes them to another repository for use by external developers.

What do you think about that?

**Comment by nghialv** [comment]
@yliu-d Recently, we updated our repository to contain all generated code such as proto code for model and config packages.
Therefore I think now you can use them by importing them directly without any problem.

Thank you for your report.

**Comment by yliu-d** [comment]
Sorry it took me a while to get back to pipecd again. Thank you for generating TS definitions for those protobuf messages, but my use case is actually different: I plan to create typescript program as wrapper to helm commands and pipecd config yaml used in helm commands, hence what is really needed is to generate Typescript definitions from those `XXSpec` golang structs under https://github.com/pipe-cd/pipecd/tree/master/pkg/config .
