### ISSUE TITLE
Replace instead of kubectl apply to avoid annotation size limit being exceeded

### ISSUE THREAD

**Issue by kentakozuka** [pipe-cd/pipecd#3173]
**What would you like to be added**:

If k8s object config is too large, `kubectl apply` fails with an error saying `metadata.annotations: Too long: must have at most 262144 characters` because `last-applied-configuration` is too large to fit.
Need to add the feature to replace Kubernetes object instead of `kubectl apply`.
A solution to the problem is introduced in ArgoCD by adding `Replace=true` sync option (See bellow link).

[ArgoCD: Replace Resource Instead Of Applying Changes](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#replace-resource-instead-of-applying-changes)

**Comment by nghialv** [comment]
https://blog.atomist.com/kubernetes-apply-replace-patch/#:~:text=The%20replace%20command%20behaves%20kind,resource%20using%20the%20modified%20spec.

**Comment by nghialv** [comment]
So we should add an option for the Kubernetes application to allow using `kubectl replace` instead of `kubectl apply`.

**Comment by nghialv** [comment]
https://github.com/pipe-cd/pipecd/blob/master/pkg/app/piped/cloudprovider/kubernetes/kubectl.go#L60

**Comment by nghialv** [comment]
https://pipecd.dev/docs/user-guide/configuration-reference/#kubernetes-application
