### ISSUE TITLE
Remove Environment concept from models

### ISSUE THREAD

**Issue by khanhtc1202** [pipe-cd/pipecd#3221]
**What would you like to be added**:

**Why is this needed**:

**Comment by knanao** [comment]
Is this issue already resolved?

**Comment by khanhtc1202** [comment]
it's not. We only removed environment related API, not the environment model

**Comment by khanhtc1202** [comment]
fyi, this issue is about remove all the environment concept from pipecd models, so it's not about only remove the environment model, we have to remove env_id in each models as well 👀
