### ISSUE TITLE
Remove environment concept from actions-plan-preview

### ISSUE THREAD

**Issue by Hosshii** [pipe-cd/pipecd#3252]
**What would you like to be added**:
Remove environment concept from actions-plan-preview

**Why is this needed**:
Currently actions-plan-preview displays `env` on comment.  This should removed because env concept will be removed from pipecd.

**Comment by nghialv** [comment]
Currently, the env name can be determined by extracting the value of the `env` label.
So please show it when that label is existing, otherwise, let's omit it.

**Comment by nghialv** [comment]
> Currently, the env name can be determined by extracting the value of the `env` label. So please show it when that label is existing, otherwise, let's omit it.

@Hosshii @khanhtc1202 what do you think?

**Comment by Hosshii** [comment]
I think this is good.
Should I change not only plan-prewview, but also pipectl etc?

**Comment by nghialv** [comment]
@Hosshii Yes, I guess we have to update a couple of places.

- Add application labels to PlanPreviewResult https://github.com/pipe-cd/pipecd/blob/master/pkg/model/planpreview.proto#L52
- Update piped to populate app labels while building results (env was removed by [pkg/app/piped/planpreview/builder.go](https://github.com/pipe-cd/pipecd/pull/3229/files#diff-bba8f78d20c53c44aaace9b8716fd75148ec3ad9bc18479e5eb13b4e5bc9c49b))
- Update pipectl and actions-plan-preview to use the value of "env" label https://github.com/pipe-cd/pipecd/blob/master/pkg/app/pipectl/cmd/planpreview/planpreview.go#L276

**Comment by Hosshii** [comment]
Ok, thank you for explaining!
