### ISSUE TITLE
Add action link to the GitHub comment of action-plan-preview

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipecd#3262]
**What would you like to be added**:

**Why is this needed**:

**Comment by Hosshii** [comment]
Thank you.
I'm not sure where to add it, should I add it in the omitted comments section?

**Comment by Hosshii** [comment]
@nghialv

**Comment by nghialv** [comment]
@Hosshii How about adding it as a new badge of the comment?

Like this.

```
[![ACTIONS](https://img.shields.io/static/v1?label=PipeCD&message=Action_Log&style=flat)](link-to-the-action)
```

![Screen Shot 2022-02-16 at 16 25 17](https://user-images.githubusercontent.com/1751755/154216165-34d69faa-64a5-4f3c-9924-8c931a31eb72.png)

**Comment by Hosshii** [comment]
This is very good. I'll do this. Thank you!
