### ISSUE TITLE
Wrong message after registering application from the suggestion form

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipecd#3401]
**What happened**:

![Screen Shot 2022-03-16 at 23 07 06](https://user-images.githubusercontent.com/1751755/158608480-ee07ce4e-77ab-47f1-9190-6d445e2e5ed6.png)

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

**Comment by khanhtc1202** [comment]
Staled!
