### ISSUE TITLE
Enable eventwatcher replacement with key-pair value pattern

### ISSUE THREAD

**Issue by khanhtc1202** [pipe-cd/pipecd#3506]
**What would you like to be added**:

Currently, the PipeCD eventwatcher value replacement only supports value under a simple query path like `$.spec.xyz[1].yy...` (only index and key name allowed). It would be better if we support key-value pair query as well.

Note: even better if we can support wildcard queries.

ref [kubectl docs](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/#:~:text=Index%20by%20key%2Dvalue%20pair)

**Why is this needed**:

**Comment by khanhtc1202** [comment]
Created issue on go-yaml repository https://github.com/goccy/go-yaml/issues/290

**Comment by t-kikuc** [comment]
I close this issue because this is almost the same as [Support multiple value updates in EventWatcher] #5088
