### ISSUE TITLE
Improve plan-preview comment message

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipecd#3510]
**What would you like to be added**:
Instead of showing 
> No resource changes were detected but the following apps will also be triggered

Just show it as normal detected applications with "no change" in summary.

https://github.com/pipe-cd/pipecd/blob/master/tool/actions-plan-preview/planpreview.go#L214

**Why is this needed**:

**Comment by khanhtc1202** [comment]
Planpreview comments are changed pretty much, so staled!
