### ISSUE TITLE
Secret management for helm chart.

### ISSUE THREAD

**Issue by mugioka** [pipe-cd/pipecd#3542]
**What would you like to be added**:
I would like to have the ability to encrypt specific helm values like [helm-secrets](https://github.com/jkroepke/helm-secrets), or the ability to support sops/helm-secrets like [ArgoCD](https://github.com/jkroepke/helm-secrets/wiki/ArgoCD-Integration).

**Why is this needed**:
The values.yaml may contain confidential information, and those values need to be encrypted in order to manage by Git repository.

I looked at [this](https://pipecd.dev/docs/user-guide/secret-management/) and it appears that helm values are not supported. If it is supported, an example would be appreciated.

**Comment by nghialv** [comment]
@mugioka Thanks for your issue.

Yes, with the Secret Management feature you can encrypt any secret and embed it in any files (including `values.yaml` in your case).

You can see this example,

The secret is encrypted and then embedded in a `service.yaml` file 
https://github.com/pipe-cd/examples/blob/master/cloudrun/secret-management/app.pipecd.yaml#L8-L13
https://github.com/pipe-cd/examples/blob/master/cloudrun/secret-management/service.yaml#L18

To see how it is working actually, please check out this playground environment.
https://play.pipecd.dev/applications?project=play

**Comment by mugioka** [comment]
Thank you for your reply.
I see, I will try this feature in values.yaml.

Thanks!

**Comment by nghialv** [comment]
👍
