### ISSUE TITLE
nodeSelector ?

### ISSUE THREAD

**Issue by m4dm4rtig4n** [pipe-cd/pipecd#3597]
Hello,

It's possible to add in helm chart deployment chart to add nodeSelector ?

Exemple :
  nodeSelector:
    kubernetes.io/hostname: k3smaster1

Thx

**Comment by nghialv** [comment]
@m4dm4rtig4n Hi, thank you for your issue.

Could you please tell me which Helm chart you want to specify `nodeSelector`?
The helm chart of `PipeCD` (https://github.com/pipe-cd/pipecd/tree/master/manifests/pipecd)  or `Piped` (https://github.com/pipe-cd/pipecd/tree/master/manifests/piped) or your application?

**Comment by m4dm4rtig4n** [comment]
I think it would be good to add the feature on the 2 charts

**Comment by nghialv** [comment]
@m4dm4rtig4n I see.
I have just re-checked them and I found that the Piped agent chart is already containing the `nodeSelector` option.
You can check it out here. https://github.com/pipe-cd/pipecd/blob/master/manifests/piped/values.yaml#L80

About the chart for the control plane, yes I think it does not exist currently.
https://github.com/pipe-cd/pipecd/blob/master/manifests/pipecd/values.yaml

Could you please send a pull request to add that field?
