### ISSUE TITLE
Suggest labels added to notification

### ISSUE THREAD

**Issue by golemiso** [pipe-cd/pipecd#3600]
**What would you like to be added**:

It would be nice if the `labels` are added to the notification.

**Why is this needed**:

The document says `env` (such as dev, stg...) is now recommended to put  into a map `labels`.
It is nice to be able to know the `env` from the notification.

**Comment by nghialv** [comment]
@golemiso Hi, thank you for your issue.

Absolutely agree about that.

One vote from me to have that feature. 👍
