### ISSUE TITLE
Failed to push when multiple events were fired within checkInterval

### ISSUE THREAD

**Issue by inobu** [pipe-cd/pipecd#3605]
**What happened**:
If you issue an event to the event register at about the same time, it will be determined that the remote branch has been rewritten and git push will be rejected.

**What you expected to happen**:
Can be pushed without being rejected

**How to reproduce it**:
Issue an event to the event register on CI almost at the same time

**Comment by nghialv** [comment]
@inobu Hi, thank you for your issue.

@knanao Could you check this issue?

**Comment by knanao** [comment]
@nghialv 
Sure.

@inobu 
I'm sorry for my replying late.

Please let me confirm one point.
Was it the same the piped which handles each event?

**Comment by inobu** [comment]
@knanao 
No, it was'nt.
For example, it can also occur by using different piped at the same time with labels.

**Comment by knanao** [comment]
Hi, @inobu.
We finally fixed this bug and released a new version `v0.32.0`.
That's why let me close this one.

Thank you for your report.
