### ISSUE TITLE
Better UI that helps users to know if the piped has been updated successfully or not

### ISSUE THREAD

**Issue by khanhtc1202** [pipe-cd/pipecd#3649]
**What would you like to be added**:

Currently, only version of piped is shown on the web console, and users can be aware of version changing stub. It would be better if the piped configuration updating is shown in some ways as well.

**Why is this needed**:

**Comment by khanhtc1202** [comment]
idea: currently, the launcher has to fetch the piped configuration somewhere and use it to start up a new piped instance. We can use that link to reference the piped configuration and store it in the piped model. With that field in the piped model, we can show something like: "current running piped configuration" on the piped list page of the web console.

https://play.pipecd.dev/settings/piped?project=play

**Comment by Szarny** [comment]
Here are some ideas for implementation.

**i. Store the URL where the piped config is served**
- Piped passes the URL where its own config is served to the control plane at startup.
- In the piped setting screen of the Web UI, selecting an item from the menu to open a piped config will open its URL in a new tab.

**ii. Store the piped config**
- Piped passes its own config to the control plane at startup.
- In the piped setting screen of the Web UI, selecting an item from the menu to open a piped config will show the corresponding piped config in the alert modal.
- Piped config may has credential info, so a mechanism for masking fields that may contain credential info is needed.

<img src="https://user-images.githubusercontent.com/26561120/169992823-2ad2a9ef-f9cb-4768-b4c7-fc51bc9c3b38.png" width=800>

<img src="https://user-images.githubusercontent.com/26561120/169992934-31b69fbb-fa98-4854-9f9e-d7ac44c93367.png" width=400>

**Comment by khanhtc1202** [comment]
That's nice, one vote from me to store masked configuration in piped model 👍

**Comment by nghialv** [comment]
OK. Let's mask the config at Piped side before sending it to the control plane and show the masked one on the web console.

**Comment by Szarny** [comment]
@khanhtc1202  @nghialv  
Regarding masking confidential fields, which of the following methods do you think is the best?

1. **Delete confidential fields**
Easy to implement, but users won’t be able to know if the field is not set or deleted by this feature

2. **Override confidential fields with some string (e.g. XXXXX)**
The first idea.

3. **Override confidential fields with its hash value (e.g. 3f786f...)**
Users with knowledge of confidential information can check if its value has been updated to the intended one, but it may be hard to implement.

**Comment by nghialv** [comment]
Number 2 looks nice.

**Comment by khanhtc1202** [comment]
If the updated piped configuration only changes the confidential values compare to the previous one, we should not mask the field value completely with `*` chars. I think something like `fooBar: *******ergeww` (not full mask) is better in this case. wdyt?

**Comment by Szarny** [comment]
> we should not mask the field value completely

I think it's a good approach, but there are a few cases where we need to be careful. e.g., the confidential field value is too short to reveal, or the suffix is still the same after the update.

**Comment by khanhtc1202** [comment]
yeh, it depends on how we implement the masking logic, so I think it should be fine to implement simple logic that handles well-known cases (as you mentioned) or just handle case masking too short or such; others can be handled later. It up to you, feel free to add TODO or create other issue for that later if you want 😄

**Comment by Szarny** [comment]
I understood, thank you for your comment :pray:

**Comment by nghialv** [comment]
I will vote to mask all as `***` for the sake of simplicity and safety at this time.
