### ISSUE TITLE
Error message shown empty on insight page load

### ISSUE THREAD

**Issue by khanhtc1202** [pipe-cd/pipecd#3650]
**What happened**:

**What you expected to happen**:

<img width="465" alt="Screen Shot 2022-05-23 at 11 46 37" src="https://user-images.githubusercontent.com/32532742/169748834-534f9209-616e-4d29-98c5-10859b55413a.png">

**How to reproduce it**:

access to insight page

**Environment**:
- `piped` version: v0.31.0
- `control-plane` version: v0.31.0
- Others:

**Comment by Szarny** [comment]
This error seems to be caused by an exception in `web/src/modules/deployment-frequency/index.ts` `fetchDeploymentFrequency` that is not being handled correctly.

```ts
export const fetchDeploymentFrequency = createAsyncThunk<
  InsightDataPoint.AsObject[],
  void,
  { state: AppState }
>(`${MODULE_NAME}/fetch`, async (_, thunkAPI) => {
  const state = thunkAPI.getState();

  const data = await InsightAPI.getInsightData({
    applicationId: state.insight.applicationId,
    metricsKind: InsightMetricsKind.DEPLOYMENT_FREQUENCY,
    rangeFrom: state.insight.rangeFrom,
    rangeTo: state.insight.rangeTo,
    offset: state.insight.offset,
  });

  if (data.type == InsightResultType.MATRIX) {
    return data.matrixList[0].dataPointsList;
  } else {
    return [];
  }
});
```

**Comment by khanhtc1202** [comment]
Nice catch 🙌  Would be best if you can send a fix PR, I will add it to the next release 😄

**Comment by Szarny** [comment]
The real cause was that the error message was an empty value.
I have created a PR to fix it: https://github.com/pipe-cd/pipecd/pull/3692
