### ISSUE TITLE
UX improvement related to "Show Piped configuration" feature

### ISSUE THREAD

**Issue by Szarny** [pipe-cd/pipecd#3712]
**What would you like to be added**:

- Expand the width of the dialog to display the Piped configuration.
- Display Piped configuration with YAML syntax highlight.
- If the Piped configuration has not yet been loaded, make the corresponding list item disabled.
- others?

**Why is this needed**:

To improve UX when users use this feature.

**Comment by khanhtc1202** [comment]
how about removing empty/null field? There are many fields with only empty string ("") and null values are showing in the output dialog.

**Comment by Szarny** [comment]
@khanhtc1202 

> removing empty/null field

Do you think the logic to do this should be done on the web console or the server?

**Comment by khanhtc1202** [comment]
I think it should be handled by Piped since we have the struct at that point and if we have to do that on the web console, we need to unmarshal it again to struct (web console only get a string)

**Comment by Szarny** [comment]
I understood, thank you for your advice.
