### ISSUE TITLE
Cannot deploy app successful with ecs provider

### ISSUE THREAD

**Issue by hblab-ngocnd** [pipe-cd/pipecd#3847]
**What happened**:

I try deploy amazon ecs task with pipeCD, on pipeCD console show failure status but when i check on aws console, i see new task are created with new revision.

This is error message on pipeCD console

> Failed to rolling out ECS task set for service xxxx: failed to create ECS task set arn:xxx:29: operation error ECS: CreateTaskSet, https response error StatusCode: 400, RequestID: f83d50b0-5c3f-4919-bb5e-c5078df993f7, InvalidParameterException: Container Name can not be blank.

But i'm sure i specified the container name in taskdef.yml file below:
```
containerDefinitions:
  - command: null
    image: xxxx:latest
    name: xxxxxx
```
**What you expected to happen**:
Deploy successful

**How to reproduce it**:

- Create app with kind is `ECS`
- Setting required info
- Push code to repo
- Show pipeCD console log

**Environment**:
- `piped` version: v0.34.0
- `control-plane` version: v0.35.1
- Others:

**Comment by khanhtc1202** [comment]
caused by wrong setting so close 👍
