### ISSUE TITLE
URL miss

### ISSUE THREAD

**Issue by SakataAtsuki** [pipe-cd/pipecd#4024]
https://github.com/pipe-cd/pipecd/blob/8e01b46f1c16132003650c4fed53301b40b63713/web/src/components/application-form/index.tsx#L218

This page returns 404.

I think `https://pipecd.dev/docs/user-guide/managing-application/adding-an-application/#picking-from-a-list-of-unused-apps-suggested-by-pipeds` is correct.

**Comment by khanhtc1202** [comment]
Nice catch 👍 
Could you make a fix PR for this 😄

**Comment by SakataAtsuki** [comment]
Okey.

**Comment by SakataAtsuki** [comment]
PR: [Fix the invalid link #4027](https://github.com/pipe-cd/pipecd/pull/4027)
