### ISSUE TITLE
Support pipectl version control with asdf

### ISSUE THREAD

**Issue by stormcat24** [pipe-cd/pipecd#4076]
**What would you like to be added**:

Currently, the pipectl installation method is traditional a little.
https://pipecd.dev/docs/user-guide/command-line-tool/

In cloud native, kubectl, helm, gcloud and eksctl have plugins for installing with asdf.
https://github.com/asdf-vm/asdf-plugins/tree/master/plugins

**Why is this needed**:
In order to increase the number of users of PipeCD, collaboration with popular ecosystems is very beneficial. 
However, this idea is not a high priority 😎

**Comment by khanhtc1202** [comment]
Nice point, will add it to our pocket soon 👍

**Comment by funera1** [comment]
Created a [PR](https://github.com/asdf-vm/asdf-plugins/pull/745) to be added to asdf.

**Comment by stormcat24** [comment]
I have verified that it works. Great 👍 
```
$ asdf install pipectl latest
* Downloading pipectl release 0.41.4...
pipectl 0.41.4 installation was successful!
```

Users need documentation for this installation method.
