### ISSUE TITLE
Shorten expiration of session on WebUI 

### ISSUE THREAD

**Issue by kevin55156** [pipe-cd/pipecd#4107]
**What would you like to be added**:
Shorten the expiration of session on WebUI.

**Why is this needed**:
Long expiration of session induces security risks.

**Comment by khanhtc1202** [comment]
Maybe better to make it configurable via ControlPlane configuration.
https://pipecd.dev/docs/user-guide/managing-controlplane/configuration-reference/#sharedssoconfig
