### ISSUE TITLE
Add the status of failing to load application config file

### ISSUE THREAD

**Issue by knanao** [pipe-cd/pipecd#4149]
**What would you like to be added**:
Currently, there is no way to check the error failing to load app config on the console.
It's useful to make it possible to debug its error without checking the log every time. 

https://github.com/pipe-cd/pipecd/blob/master/pkg/app/piped/trigger/trigger.go#L226

**Why is this needed**:

**Comment by funera1** [comment]
I would like to add the following three functions for convenience
- Get application-id from application-name
- Get a list of deployment-ids from application-id
- Get deployment's stage log from deployment-id
