### ISSUE TITLE
Run codegen with GitHub Actions when *.pb.go has merge conflict.

### ISSUE THREAD

**Issue by funera1** [pipe-cd/pipecd#4192]
When *.pb.go has merge conflict, I want to run make gen/code with GitHub Actions to resolve the merge conflict.
Consider using workflow_dispatch.

**What would you like to be added**:

**Why is this needed**:

**Comment by khanhtc1202** [comment]
We would like to ensure no auto-generated code is added via CI, changes should be manually update by developers
