### ISSUE TITLE
[ piped config ] Add all resources for `appStateInformer.includeResources`

### ISSUE THREAD

**Issue by tetsuya28** [pipe-cd/pipecd#4213]
**What would you like to be added**:
Currently, we have to add all resources, which [buildin api versions list](https://github.com/pipe-cd/pipecd/blob/3e209562657b0a6654ea85c13c1f6612c2aba78a/pkg/app/piped/platformprovider/kubernetes/resourcekey.go#L24) does not include, to `appStateInformer.includeResources` in piped config, like `cert-manager.io/v1`, etc.
[Configuration reference | PipeCD](https://pipecd.dev/docs/user-guide/managing-piped/configuration-reference/#kubernetesresourcematcher)
Can I set all resources to `appStateInformer.includeResources` ?

**Why is this needed**:
That operation leads to miss some resources in a piped.

**Comment by knanao** [comment]
@tetsuya28  Hi, thank you for your issue.

As you mention, this should be independent of the fixed supported list.
Hence, let me think about how to resolve this.
