### ISSUE TITLE
[ECS] Cancel with rollback does not remove canary created tasks

### ISSUE THREAD

**Issue by khanhtc1202** [pipe-cd/pipecd#4329]
**What happened**:

While deploying ECS applications with canary-related stages, cancel with rollback command does revert the application version to the previous one but doesn't remove canary stage created tasks. The reason due to canary stage created and connected canary tasks to the LB target group, and that keeps those tasks available to handle requests to that target group

**What you expected to happen**:

Remove canary stages created task on deployment cancel

**How to reproduce it**:

**Environment**:
- `piped` version: v0.43.0
- `control-plane` version: v0.43.0
- Others:

**Comment by ductnn** [comment]
Has anyone done it yet?
@khanhtc1202 can you assign this issue to me? :D

**Comment by khanhtc1202** [comment]
For sure, thank you 😄
