### ISSUE TITLE
More metrics about deployment workflow that be exported by Piped

### ISSUE THREAD

**Issue by khanhtc1202** [pipe-cd/pipecd#4337]
**What would you like to be added**:

**Why is this needed**:

Though we already support some metrics export via piped admin server (at /metrics), users need more deployment metrics for a better monitoring board to watch piped operations.

**Comment by kentakozuka** [comment]
@khanhtc1202
How about adding the metrics below?

## Metrics to be added

The number of Deployments

- Prometheus Metrics Type
  - Count
- label
  - Deployment status
  - application kind
  - Platform Provider
  - project
  - piped
- when to observe
  - scheduler changes deployment status to RUNNING
  - scheduler changes deployment status to FAILURE
  - scheduler changes deployment status to SUCCESS

**Comment by khanhtc1202** [comment]
I guess the deployment status RollBack/Cancel should be listed as well. Also, users want to set an alert on long-run unfinished deployment so that they can reset/cancel it by hand; thus we need metrics like time from the start for deployment metrics as well 🤔

**Comment by kentakozuka** [comment]
@khanhtc1202
Updated 👍 

## Metrics to be added

Deployment status (`deployment_status`)

- Prometheus Metrics Type
  - Gauge (always 1)
- label
  - Deployment ID
  - Deployment status
  - application kind
  - Platform Provider
  - project
  - piped

## How to count the number of deployments by status

PromQL
```
count by (status) (count_over_time(deployment_status{project="A"}[24h]))
```

## How to detect long running deployments

PromQL
```
sum_over_time(deployment_status{status="running"}[1h:1m]) >= 60 and deployment_status{status="running"} == 1
```

- Count the number of times deployment is running in the past 1h and check if that exceeds 1h(60m).
AND
- Check if the deployment is still running.

**Comment by khanhtc1202** [comment]
@kentakozuka Thanks for the detailed explanation 🙏 The current design is LGTM, and I guess we can start implementing to see whether that's usable or not 👍 Also, the time window for detecting long-running deployment would be best if we make it changeable (I guess we are on the same page already 😄 )
