### ISSUE TITLE
kubectl apply with custom args (like --server-side) is not possible.

### ISSUE THREAD

**Issue by FabianKnapp** [pipe-cd/pipecd#4342]
**What would you like to be added**:
Enable custom args for kubectl apply or implement a switch for often used --server-side argument.

**Why is this needed**:
https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack e.g., needs --server-side as argument.

**Comment by khanhtc1202** [comment]
Hi @FabianKnapp, thanks for pointing this out 👍 Will add a fix for this by adding pipecd annotation for resources that want to be server-side applied (just as we do with `LabelSyncReplace` annotation, ref [code](https://github.com/pipe-cd/pipecd/blob/master/pkg/app/piped/platformprovider/kubernetes/kubernetes.go#L33)).

**Comment by FabianKnapp** [comment]
Thank you @khanhtc1202 !  Appreciate this!
