### ISSUE TITLE
Support Terraform import block

### ISSUE THREAD

**Issue by golemiso** [pipe-cd/pipecd#4349]
**What would you like to be added**:

[Terraform v1.5.0-beta2](https://github.com/hashicorp/terraform/releases/tag/v1.5.0-beta2) has new feature `import block`.
I tried that with PipeCD and faced an error.

error message:
```
reason: failed while calculating diff, unable to parse plan output
```

plan result with import block (this occurs parse-error):
```
Plan: 1 to import, 11 to add, 0 to change, 0 to destroy.
```

**Why is this needed**:

**Comment by khanhtc1202** [comment]
Hi @golemiso, thanks for reporting. Just want to confirm, did you try that with this configuration set to `v1.5.0-beta2` 👀 
https://pipecd.dev/docs/user-guide/configuration-reference/#terraformdeploymentinput:~:text=No-,terraformVersion,-string

**Comment by golemiso** [comment]
I did.

`unable to parse plan output` occurred because of regexp.
https://github.com/pipe-cd/pipecd/blob/534e95756010012d6561e2f5ba5d945cf7c9bd5a/pkg/app/piped/platformprovider/terraform/terraform.go#L316
