### ISSUE TITLE
[docs] Improve SSO description

### ISSUE THREAD

**Issue by sivchari** [pipe-cd/pipecd#4353]
**What would you like to be added**:

I think [Authentication and authorization](https://pipecd.dev/docs/user-guide/managing-controlplane/auth/) is unclearly description (e.g. Configuring the PipeCD’s user groups description). 

**Why is this needed**:

A clearly description helps developers to want to installation PipeCD.

**Comment by khanhtc1202** [comment]
Updated the docs reflect that, so close.
