### ISSUE TITLE
Improve GitHub client message when it's failed

### ISSUE THREAD

**Issue by sivchari** [pipe-cd/pipecd#4359]
**What would you like to be added**:

The event-watcher pushes a commit to main branch of GitHub when event is registered by someone. But if the repository prohibit to do push, this event will be failed. Then, the event-watcher returned `ErrBranchNotFresh`. The message is wrong and developers is confused as to why is this branch isn't fresh. 
I propose a 2 way. the one is piped returns more clearly message. In the other hand, piped uses GitHub client (e.g. google/go-github). wdyt ?

**Why is this needed**:

More clearly error message.

**Comment by hungran** [comment]
@sivchari um not sure how can make massage more clearly when doesn't have permission to push,
in almost cases, will return `error: failed to push some refs to` 
+1 if we can consider to use `go-github`
