### ISSUE TITLE
asdf cannot resolve dependencies

### ISSUE THREAD

**Issue by kentakozuka** [pipe-cd/pipecd#4376]
**What happened**:

asdf does not resolve dependencies when plugins are added.

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

**Comment by khanhtc1202** [comment]
related to issue #1089

**Comment by kentakozuka** [comment]
- The asdf aws-sam-cli plugin depends on asdf-pyapp, a plugin to use python apps like normal commands.
- asdf-pyapp depends on python.

As piped-base image has no python, I thought there are three ways to do this.
- Install with asdf python plugin
- Add apt get python to build base image
- Use python:X.X.X-alpineX.X for FROM of the base image


For 1 and 2, you will need to install more tools. I also tried to specify python in `externalTools` on piped, but it failed with timeout. This may be a problem with installing python on alpline itself, and according to [this article](https://pythonspeed.com/articles/alpine-docker-python/), because of the lack of various optimization tools.

So I tentatively tried the 3rd option and `sam --version` succeeded in the deployment step using piped on gke.

**Comment by kentakozuka** [comment]
## Install Python plugin with asdf

I also tried to install Python plugin on piped agent with asdf. I changed the base image of python-base to `ubuntu:22.04` and installed the requirements for python.

**Image Size**

|| base | piped-base | piped |
| -- | -- | -- | --
|alpine:3.12.1 | 5MB | 245MB | 312MB|
|ubuntu22.04 | 69MB | 664MB | 730MB|


**Minor notices**
- Installing python with asdf on CPU:2, memory:2G pod takes 4.5mins. (Now the timeout is hard-coded as 5mins)
- If the `externalTools` is declared in `app.piped.yaml` sam cannot find the right python version and fails to be installed. (It succeeded if the `externalTools` is declared in piped config.)
- When the `externalTools` is declared in piped config, the installation is executed asynchronously in the startup.  It is possible that deployments(which have custom sync steps) run before the required plugins are installed.

<details>
<summary>tool/piped-base/Dockerfile</summary>

```dockerfile
FROM ubuntu:22.04

ARG PIPED_USER=piped
ARG PIPED_USER_GROUP=piped
ARG PIPED_UID=1000
ARG PIPED_GID=1000

ENV HOME=/home/${PIPED_USER}
ENV PIPED_TOOLS_DIR="${HOME}/.piped/tools"
ENV PATH="${PIPED_TOOLS_DIR}:${PATH}"

COPY install-helm.sh /installer/install-helm.sh
COPY install-kubectl.sh /installer/install-kubectl.sh
COPY install-kustomize.sh /installer/install-kustomize.sh
COPY install-terraform.sh /installer/install-terraform.sh

RUN \
    groupadd -r -g $PIPED_GID $PIPED_USER_GROUP && \
    useradd -r -u $PIPED_UID -g $PIPED_USER_GROUP -d $HOME $PIPED_USER && \
    apt-get update && \
    apt-get upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" && \
    apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
        ca-certificates \
        git \
        openssh-client \
        curl \
        zip \
        # Required for python
        build-essential libbz2-dev libffi-dev liblzma-dev libncursesw5-dev libreadline-dev libsqlite3-dev libssl-dev uuid-dev zlib1g-dev && \
    update-ca-certificates && \
    mkdir -p ${PIPED_TOOLS_DIR} && \
    # Pre-install the default version of helm.
    /installer/install-helm.sh && \
    # Pre-install the default version of kubectl.
    /installer/install-kubectl.sh && \
    # Pre-install the default version of kustomize.
    /installer/install-kustomize.sh && \
    # Pre-install the default version of terraform.
    /installer/install-terraform.sh && \
    # Delete installer directory.
    rm -rf /installer && \
    apt-get clean && \
    chown -R $PIPED_USER:$PIPED_USER_GROUP $HOME && \
    chmod 770 -R $HOME && \
    # Set bash as default shell.
    rm /bin/sh && ln -s /bin/bash /bin/sh

USER $PIPED_USER
```
</details>
