### ISSUE TITLE
Upgrade codegen base container image to use go v1.20.5

### ISSUE THREAD

**Issue by khanhtc1202** [pipe-cd/pipecd#4379]
Currently, the pipecd codegen workflow still uses the previous v0.37.x codegen container image, which is based on `golang:v1.19.3-alpine3.15` container image.

**Comment by kentakozuka** [comment]
gen workflow fails in generating mock because `errors.Join` was introduced in v0.44.2, which is only available for go1.20.

```sh
# github.com/pipe-cd/pipecd/pkg/app/piped/platformprovider/kubernetes
../pkg/app/piped/platformprovider/kubernetes/loader.go:99:16: undefined: errors.Join
note: module requires Go 1.20
# github.com/pipe-cd/pipecd/pkg/app/piped/platformprovider/kubernetes
../loader.go:99:16: undefined: errors.Join
note: module requires Go 1.20
go: finding module for package github.com/golang/mock/mockgen/model
go: finding module for package github.com/pipe-cd/pipecd/pkg/app/piped/platformprovider/kubernetes
go: downloading github.com/pipe-cd/pipecd v0.44.2
# github.com/pipe-cd/pipecd/pkg/app/piped/platformprovider/kubernetes
/go/pkg/mod/github.com/pipe-cd/pipecd@v0.44.2/pkg/app/piped/platformprovider/kubernetes/loader.go:99:16: undefined: errors.Join
note: module requires Go 1.20
2023/07/12 13:00:06 Loading input failed: exit status 2
```

**Comment by kentakozuka** [comment]
was it proto related problem that we cannot use the latest image?

**Comment by khanhtc1202** [comment]
well, the latest codegen image which based on go 1.20.5 can not generate proto as expected, that is why we still use the old one. Maybe the problem on proto tool chain 🤔

**Comment by kentakozuka** [comment]
Let's find out the problem of this 👍  Otherwise, we cannot pass the CI workflow.

**Comment by khanhtc1202** [comment]
Fixed by https://github.com/pipe-cd/pipecd/pull/4498
