### ISSUE TITLE
Wrong json tag in ECS task definition

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipecd#4384]
**What happened**:

- https://github.com/pipe-cd/pipecd/blob/master/pkg/config/application_ecs.go#L46

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

**Comment by khanhtc1202** [comment]
We're using that name to unify with the AWS docs. 😄 
ref: https://docs.aws.amazon.com/cli/latest/reference/ecs/run-task.html#:~:text=Developer%20Guide%20.-,awsvpcConfiguration,-%2D%3E%20(structure)
[9:44](https://cyberagent.slack.com/archives/D01FV4SFGGJ/p1686494648510339)
