### ISSUE TITLE
Dynamic mentions to slack

### ISSUE THREAD

**Issue by taigaskg** [pipe-cd/pipecd#4417]
**What would you like to be added**:
I think it is possible to send Slack notifications of Deployment WAIT APPROVALs with the current functionality. It may also be possible to add pre-defined mentions.
I would like to be able to dynamically add mentions to a specific person who triggered the Deployment.

For example, if I have set up slack id's for two people, A and B, when person A triggers a deployment, I would like to be able to send mentions only to person A, and not to person B.

**Why is this needed**:
Our team has a trunk-based development policy.
Since multiple releases are made per day, we have introduced a WAIT APPROVAL stage in the pipeline as a final check to see if a release is ready to be rolled out.
However, since it takes some time to reach the WAIT APPROVAL stage, we feel that we can use our time more effectively if we can send notifications only to those who triggered the release when the release reaches the WAIT APPROVAL stage.

**Comment by khanhtc1202** [comment]
For sure, thanks 🙏

**Comment by khanhtc1202** [comment]
https://github.com/pipe-cd/pipecd/pull/4583#issuecomment-1709845853

Continue for this comment, I think `Only notify the user who triggers the deployment` is good, but not every team wants that. Let's say, in our (PipeCD team) use-case; we want the review from other users - not the one who triggers the deployment to approve the WAIT_APPROVAL stage. So, making that an optional setting could be a better choice. WDYT? @kentakozuka @seitarof

**Comment by seitarof** [comment]
@khanhtc1202 
I also believe that this feature should be optional.
Moreover, I think this feature should be applicable not only to the WAIT_APPROVAL stage but also to other stages.

In the case of your team's use-case, you may not need to use this feature at all.
You should be notified with the existing settings as follows.
```
  notification:
    mentions:
      - event: DEPLOYMENT_WAIT_APPROVAL
        slack:                 # optional
          - {slack-uid}
          - {slack-uid}
          - {slack-uid}
```

I believe the best way to notify only the user who triggered the deployment is as follows. With this configuration, backward compatibility is ensured.(setting name is open to consideration)
```
  notification:
    mentions:
      - event: DEPLOYMENT_WAIT_APPROVAL
        dynamics:                 # optional
          - git: {github-id}
            slack: {slack-uid}
```

Also, to notify both the trigger user and the head of development, you should set it as follows.
The "slack" field represents users who will be notified for certain, while the "dynamics" (tentative name) field represents a list of users who will be notified only when they trigger an event.
```
  notification:
    mentions:
      - event: DEPLOYMENT_WAIT_APPROVAL
        slack:                 # optional
          - {head-of-dev-slack-uid}
        dynamics:                 # optional
          - git: {github-id}
            slack: {slack-uid}
```

I currently can't come up with any ideas other than this method...

**Comment by kentakozuka** [comment]
What I worry about this feature is that it lacks expandability.

For example, another user may want;
- notify selected users who don't commit.
- notify selected users randomly(or in round-robin)
- etc.

I like this feature, so I want it to be open to be improved 😄

**Comment by seitarof** [comment]
@kentakozuka
How about the following idea?

This is a method where `accounts` is set directly under `notifications`, and how to send it is specified by `sendType`. 
This method seems to be scalable because you only need to increase the types of `sendType`.

```
  notification:
    mentions:
      - event: DEPLOYMENT_WAIT_APPROVAL
        slack:
          - {head-of-dev-slack-uid}
        sendType: all (onlyComitter, withoutComitter, random, etc...)
    accounts:
      - git: {github-id}
        slack: {slack-uid}
```

**Comment by kentakozuka** [comment]
@seitarof 
So sorry to be late. I reconsidered this. This feature can make the notification too complex for regular usage. The configuration will be messy when another integration is added rather than Slack. (Github also does not have a feature like this or assignment of reviewers.)

It may be achieved using [run script stage](https://github.com/pipe-cd/pipecd/pull/4603).

**Comment by kentakozuka** [comment]
Feel free to open this when someone wants to discuss more ❤️
