### ISSUE TITLE
Add metric about application's state

### ISSUE THREAD

**Issue by kanata2** [pipe-cd/pipecd#4472]
**What would you like to be added**:

I want to keep track of status and events for each application. For example, I'm considering the following:

- ~~Add labels for application(like application name, id, etc...) to deployment metrics introduced in v0.44.0~~ -> #4475 
- Add metric like `argocd_app_info` in ArgoCD
  - This contains labels such as `sync_status` and `health_status` that reflect the application state in ArgoCD

**Why is this needed**:

This is because the additional application information makes it easier to understand the status of each application.

**Comment by kentakozuka** [comment]
@kanata2 Thanks for raising the issue!
Can you separate this issue into 2 different ones? So we can handle one by one 👍

**Comment by kanata2** [comment]
Done :)
