### ISSUE TITLE
Always scroll to the bottom on terraform plans preview

### ISSUE THREAD

**Issue by kurochan** [pipe-cd/pipecd#4473]
**What [happened**:](url)
I have a problem with the feature terraform plans preview. 
When I try to scroll back manually to check, it automatically scrolls to the bottom and I cannot check it.

**What you expected to happen**:
First time, it scrolls to the bottom. But after that, auto-scroll is disabled.

**How to reproduce it**:

https://github.com/pipe-cd/pipecd/assets/591247/b4c88349-8d3b-4f35-a0d5-522128a5cf8c

**Environment**:
- `control-plane` version: v0.44.1

**Comment by khanhtc1202** [comment]
@kurochan Does it happen on this page as well? 👀 
https://play.pipecd.dev/deployments/a006fb86-822c-42cb-8eb5-de4c2204dd48?project=play

**Comment by kurochan** [comment]
@khanhtc1202 The problem I point out did not occur in the play environment. That's strange 🤔

**Comment by khanhtc1202** [comment]
TBH, I got this issue sometime, but it's quite weird and hard to reproduce (on dev and locally) 😓 Let me check around that part, but due to it's hard to reproduce, it's quite hard to figure out how to fix.

**Comment by kurochan** [comment]
I found that this problem only occurs in multi-stage pipelines and  when the pipeline is running.

**Comment by khanhtc1202** [comment]
Oh, if in such case, it's the current spec. Every time the logs (of the stage) are updated, the stage log view will be updated/generated, and auto scroll to the bottom will be triggered. The point is to notify users that a new log has been added. Once the stage is finished, you can scroll wherever you want to.
https://github.com/pipe-cd/pipecd/blob/master/web/src/components/deployments-detail-page/log-viewer/log/index.tsx#L30-L32

**Comment by kurochan** [comment]
Just to confirm, is it a specification that when the log of a later stage is updated, the scroll in the log of the stage that has already finished is also updated? Seems like unnatural behavior to me 🤔

**Comment by khanhtc1202** [comment]
In such case, it's not, that would be counted as a bug 👍
