### ISSUE TITLE
Add application related labels to deployment metrics

### ISSUE THREAD

**Issue by kanata2** [pipe-cd/pipecd#4475]
Split from https://github.com/pipe-cd/pipecd/issues/4472

> I want to keep track of status and events for each application. For example, I'm considering the following:
> - Add labels for application(like application name, id, etc...) to deployment metrics introduced in v0.44.0

**Comment by kanata2** [comment]
Originally I wanted to use Grafana's state timeline in order to monitor state the application.
So I believe the application name is necessary. However, I don't think the application name is unique, so it would be good to have some information that can be filtered. (This may be enough with existing labels).

ref: https://stackoverflow.com/a/72515955

**Comment by kentakozuka** [comment]
Thanks! Let me make it clear. Once [metric about application's state](https://github.com/pipe-cd/pipecd/issues/4472) is implemented, existing deployment metrics are no longer necessary for your use case?
Actually, [argocd_app_info](https://argo-cd.readthedocs.io/en/stable/operator-manual/metrics/) looks nice :)

**Comment by kanata2** [comment]
Ah, in this case, actually yes.
However, I feel that it would be useful to have labels on the deployment metrics that can identify the application, for example, to visualize the numbers of success/failure/total of deployments etc by application.

**Comment by kentakozuka** [comment]
Sure. I talked with our team and we concluded that it would be better to add application-related labels to deployment metrics 👍 

@kanata2 Btw, would you like to implement this? ;)

**Comment by kanata2** [comment]
Thanks. Okay, I'll submit a PR later.

**Comment by kentakozuka** [comment]
We really appreciate it!
