### ISSUE TITLE
ECS deployment should wait until new version is rolled out completely

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipecd#4478]
**What would you like to be added**:

**Why is this needed**:

Currently, PipeCD exits immediately after preparing/updating new TaskDefinition and ServiceDefinition.
Because of that something users have to check the actual rolling out status on AWS console.

Therefore, I propose adding a new flag in ECS deployment configuration to force checking the rolling out status before mark the deployment as completed.

**Comment by khanhtc1202** [comment]
Ref ECS API: https://docs.aws.amazon.com/cli/latest/reference/ecs/wait/services-stable.html

**Comment by khanhtc1202** [comment]
We have to use `describe-services` API instead
ref: docs

> Wait until JMESPath query length(services[?!(length(deployments) == 1 && runningCount == desiredCount)]) == 0 returns True when polling with describe-services.
