### ISSUE TITLE
Support setting apiKey and applicationKey for AnalysisProviderDatadogConfig directly instead of just via file

### ISSUE THREAD

**Issue by kentakozuka** [pipe-cd/pipecd#4492]
**What would you like to be added**:

Currently, the AnalysisProviderDatadogConfig configuration only supports auth information to be set via file (mount to the piped container). It would be great if we could support setting those values directly via fields like `apiKeyData` and `applicationKeyData` as for other configurations.

ref: https://pipecd.dev/docs-v0.41.x/user-guide/managing-piped/configuration-reference/#analysisproviderdatadogconfig

**Why is this needed**:

**Comment by khanhtc1202** [comment]
Looks like @hungran is working on this, thanks 🙏
