### ISSUE TITLE
Improve event watcher

### ISSUE THREAD

**Issue by sivchari** [pipe-cd/pipecd#4494]
**What would you like to be added**:

I want to add a new field named pushingBranch in event-watcher configuration.

**Why is this needed**:

event-watcher can push to only handled repository, but we want to push to specify branch (e.g. we want to handles dev-event relates with dev-branch and prd-event relates with prd-branch). So, I propose to add a new field to event-watcher named `pushingBranch`. If this field is set, event-watcher pushes to the branch. This field has priority over piped-agent configuration.
What do you think ?

**Comment by sivchari** [comment]
@khanhtc1202 @kentakozuka

**Comment by khanhtc1202** [comment]
What's different between this and the one you created before 🤔 
https://github.com/pipe-cd/pipecd/issues/4360

**Comment by sivchari** [comment]
#4360 supports to create a new PR named by uuid.
This feature supports to push to a specify branch. They are similar, but slightly different.

**Comment by khanhtc1202** [comment]
@sivchari I get your point, but I think this is not how this feature should be used 😄 

Basically, the piped, which handles the application that should be triggered when the event watcher changes some files, will be the one that commits the change.

So if I were you, I would make the piped which handles the application that its manifests stored in dev-branch be the one that handles the event, thus in the piped config `spec.repository[0].branch`, I will set it to `dev-branch`. So when the CI is finished, then event pushed, the piped will be noticed, and it will change files and then push to `dev-branch` (its cloned branch - mentioned in the pipecd source code), then the application will be triggered to deploy 😄 

That way of construction is easier and not messing the CI connection to CD flow, IMO. WDYT?

**Comment by khanhtc1202** [comment]
Thanks @sivchari for the idea. If you have any idea to make event watcher feature better, feel free to create a discussion on https://github.com/pipe-cd/pipecd/discussions/ 😀
