### ISSUE TITLE
PipeCD Dockerfile for local building PipeCD docker images

### ISSUE THREAD

**Issue by jz543fm** [pipe-cd/pipecd#4506]
**What would you like to be added**:

I would like that will be added to PipeCD how to locally build PipeCD for custom usage, f.e,  if I want to change in docker image for my proper use case, it will be really helpful, because I tried to run in repository `local/` when I start it, check the release with `cat /etc/*release*`, builded from `local/` the OS is `Ubuntu 16.04`, but in pod f.e, pipecd-server, it's running on `Alpine Linux 3.13.2`, I do not know how to create custom Helm Chart or Docker image from the [Pipecd Chart Releases](https://github.com/pipe-cd/pipecd/pkgs/container/chart%2Fpipecd) and the doc will be also really helpful or some template

**Why is this needed**:

It will be helpful for devs, if they want to add some additional features to custom PipeCD Helm Chart / Docker image

**Comment by kentakozuka** [comment]
It is necessary to fix [here](https://github.com/pipe-cd/pipecd/blob/331b3239b159071c49fdd8b96ecee608b3454fe8/manifests/pipecd/templates/deployment.yaml#L125) to change the PipeCD server container image.

PRs are always welcome :)
It would be great if you create a PR for that!

**Comment by jz543fm** [comment]
Yea, I've fixed that later that image, thank's, ok.

**Comment by hungran** [comment]
yeah I've same issue when trying to make image arm64, not only `pipecd` but also `piped` here
https://github.com/pipe-cd/pipecd/blob/master/manifests/piped/templates/deployment.yaml#L31-L36
what I did for local build:

- `make build`
- some babysitting command to build the image and push image into my repository with a tag
- change the image repository name and `Chart.AppVersion` to my tag

I would like we can have option to use image tag from values. wdyt?
