### ISSUE TITLE
Support for secure management of OAuth tokens for Slack notification

### ISSUE THREAD

**Issue by GotoRen** [pipe-cd/pipecd#4510]
**What would you like to be added**:

With the release of PipeCD [v0.44.0](https://github.com/pipe-cd/pipecd/pull/4355), OAuth tokens can now be used for Slack notification settings. 
[Slack OAuth token](https://pipecd.dev/docs-dev/user-guide/managing-piped/configuring-notifications/#sending-notifications-to-slack) (`oauthToken: xxxx`) should be treated as confidential information. 
In the Piped config, we would like to read external encrypted information and send notifications to any desired Slack channel. 
For example, we can read files mounted from Kubernetes secrets, such as `spec.git.sshKeyFile` or `spec.pipedKeyFile`.

**Why is this needed**:

Slack token should be securely managed as sensitive elements.
However, Piped config does not provide a direct scheme to read Kubernetes resources such as environment variables or `ExternalSecret`.
Therefore, developers must include token information for Slack notifications in plain text within the data fields of the Piped config manifest.

**Comment by hungran** [comment]
@GotoRen  @kentakozuka @khanhtc1202 
I'd like to work on this issue

I've seen that OAuthToken is also stored as string w/o encode base64
should we change it to OAuthTokenData w/ base64 and addition OAuthTokenFile as we had `spec.git.sshKeyFile` or `spec.pipedKeyFile`

**Comment by khanhtc1202** [comment]
@hungran that is great, but I think we should make the current field deprecated first, and imtroduce the field name with suffix Data as you said. We can remove the deprecated field later.

**Comment by GotoRen** [comment]
@hungran 
I think it's a great idea !!
As @khanhtc1202  mentions, it's best to do this after deprecating an existing field.

**Comment by hungran** [comment]
Hi, 100% agreed that we should make the currrent field as deprecate (`oauthToken`)
I just have no insight for implementing that, could you give me some suggestions? @khanhtc1202

**Comment by sivchari** [comment]
Hi, I read discussion and I'm agree with your saying.
I have done this implementation. So if you are confused about the implementation, I will implement it for you.

**Comment by khanhtc1202** [comment]
@sivchari, @hungran already sent a PR #4525 as a fix for this. Feel free to review; that would be a great help 😄

**Comment by hungran** [comment]
oh I might missed the comment above, feel free to reject my PR and do it :)

**Comment by khanhtc1202** [comment]
@sivchari, are you okay to take over this? 👀

**Comment by sivchari** [comment]
@khanhtc1202 
Sorry to rate response. I've reviewed #4525 . Please final review.

**Comment by GotoRen** [comment]
Thank you @sivchari !!
