### ISSUE TITLE
Support enable selection of listener rules

### ISSUE THREAD

**Issue by moko-poi** [pipe-cd/pipecd#4530]
**What would you like to be added**:
Allow PipeCD to choose which listener rules to rewrite

**Why is this needed**:
Currently, PipeCD updates the listener rules for the default setting. 

When multiple listener rules exist, the default one is not used, preventing the use of canary release.

**Comment by khanhtc1202** [comment]
This issue changed to ensure the ECS_TRAFFIC_ROUTING stage does not change other rules than Forwarding type rule
