### ISSUE TITLE
Support more detailed custom RBAC

### ISSUE THREAD

**Issue by sivchari** [pipe-cd/pipecd#4541]
I propose to prohibit to push the quick sync button. I want the feature to allow any operation (e.g. approve, pipeline sync, etc...), but not allow certain operations. Ultimately, I think this feature will be provided as extending RBAC.  I know it's hard and too complex implementation, but I think this feature is worth to provide. What do you think ?

If this feature is already implemented, I sorry.

**Comment by kentakozuka** [comment]
We have [RBAC based on resources and actions]([docs](https://pipecd.dev/docs-v0.44.x/user-guide/managing-controlplane/auth/#configuring-the-pipecds-roles)).

The actions supported by PipeCD's RBAC were not as fine-grained as you suggest. I am not quite sure whether to change the current design to satisfy your request (Besides, as you mention, implementation can be hard 😉 ).

So I propose waiting to see other users' reactions on this issue and deciding what to do afterward.
