### ISSUE TITLE
Support container images for the ARM64 architecture

### ISSUE THREAD

**Issue by stormcat24** [pipe-cd/pipecd#4544]
**What would you like to be added**:

Build and release the container images for the ARM64 architecture. 

**Why is this needed**:

I want to run PipeCD on ARM64-based [Graviton2](https://pages.awscloud.com/rs/112-TZM-766/images/2022_0722-CMP_Slide-Deck.pdf) to reduce AWS running costs. Many AWS users will welcome the release of container images for the ARM64 architecture.

What do you think?

**Comment by hungran** [comment]
I believed this issue was solved by this
https://github.com/pipe-cd/pipecd/pull/4552

**Comment by kentakozuka** [comment]
Solved by https://github.com/pipe-cd/pipecd/pull/4552.
Feel free to reopen if this is not yet fixed 👍 
@hungran Big thanks!
