### ISSUE TITLE
Enable to keep ECS task singleton while deploy/reconcile

### ISSUE THREAD

**Issue by khanhtc1202** [pipe-cd/pipecd#4609]
**What would you like to be added**:

Having an option to enable keeping ECS tasks singleton while deploy/reconcile. Just same as Kubernetes recreate option, instead of rolling out new task/taskset before deleting the old one, we want to keep only one task running at a time.

**Why is this needed**:

**Comment by t-kikuc** [comment]
@khanhtc1202 
Could we close this issue or not (cuz it seems solved)??

**Comment by t-kikuc** [comment]
#4608 solved this.
