### ISSUE TITLE
Web ui omitted manifests changes not synced.

### ISSUE THREAD

**Issue by tetsuya28** [pipe-cd/pipecd#4634]
On PipeCD Application detail page on  web ui ( like https://xxx/applications/xxx ) , we can check manifests not synced, but when an application has many changes, the page shows `... (omitted X other changed manifests`.
So we can not check the all changes.
![ss 894](https://github.com/pipe-cd/pipecd/assets/11973270/0c5109fc-2389-41f9-a81e-01ab09a66b65)

**What would you like to be added**: Enable to show all changes.

**Why is this needed**: There is no way to check all changes which are omitted.

**Comment by kentakozuka** [comment]
the max change number is here.
https://github.com/pipe-cd/pipecd/blob/e23412307b27b8a4c3741171db555958a8e70d0a/pkg/app/piped/driftdetector/kubernetes/detector.go#L388
