### ISSUE TITLE
Exit with error status code when plan preview failed

### ISSUE THREAD

**Issue by TakumaKurosawa** [pipe-cd/pipecd#4660]
**What would you like to be added**:
Call `os.Exit(1)` when plan-preview sent an error message.

**Why is this needed**:
Plan preview CI send error comment but workflow is still succeeded.
So we have to exit with error status code when exception case.

**Comment by TakumaKurosawa** [comment]
I'd like to work on this.
I've already make PR: https://github.com/pipe-cd/pipecd/pull/4659

**Comment by t-kikuc** [comment]
This is already solved.
https://github.com/pipe-cd/pipecd/blob/972d114cfc47a4465b69e4307136b083fe9d5388/tool/actions-plan-preview/main.go#L152
