### ISSUE TITLE
Private self-hosted Git server support enhancement

### ISSUE THREAD

**Issue by duclm2609** [pipe-cd/pipecd#4674]
**What would you like to be added**: Git configuration support for custom SSH port and known hosts

**Why is this needed**: Better support for private self-hosted Git server

**Comment by hungran** [comment]
um agreed, also instead support 1 [GIT Server](https://github.com/pipe-cd/pipecd/blob/master/pkg/git/ssh_config.go#L32C1-L39C2), I would like to have multiple Git
for eg, Github, GitLab or else
wdyt @khanhtc1202  :)

**Comment by khanhtc1202** [comment]
@hungran it's great, but please note that this is one piped configuration. So maybe we don't want one piped that has multi-host configuration, we only need one for each and for other piped that handle applications on other GIT servers, we have different configurations for that piped. Wdyt? 🤔

**Comment by hungran** [comment]
um 

> @hungran it's great, but please note that this is one piped configuration. So maybe we don't want one piped that has multi-host configuration, we only need one for each and for other piped that handle applications on other GIT servers, we have different configurations for that piped. Wdyt? 🤔

ideally we could have one more PipeD in one cluster aka an environment, with that case we able to have difference git host Gitlab and Github or else, however, it might rarely happen... so yeah we could have one more PipeD guess? is this possible if there are 2 PipeD running in 1 cluster?

**Comment by anhpnv** [comment]
Hi, can you pls assign me to this issue @khanhtc1202 🙌 🙌

**Comment by ffjlabo** [comment]
Hi @anhpnv 👋  What would you want to do with this one?
