### ISSUE TITLE
[piped] Add documentation of pprof

### ISSUE THREAD

**Issue by ouchi2501** [pipe-cd/pipecd#4687]
**What would you like to be added**:

as Tite
But we should discuss where to add pprof documentation

**Why is this needed**:

piped is able to profile with pprof.
Sometimes I want to measure piped's memory and CPU usage.
It's a shame that the wonderful thing about piped's support for pprof is not mentioned in the documentation.

https://github.com/pipe-cd/pipecd/blob/f10a8e770ab8821fa402f9dde15cfa1cd11638f6/pkg/app/piped/cmd/piped/piped.go#L255-L258

**Comment by khanhtc1202** [comment]
Nice catch 👍 
How about adding it here as a new tab (named: Operation and debugging)?
https://pipecd.dev/docs-v0.45.x/user-guide/managing-piped/

**Comment by ouchi2501** [comment]
I think it's good👍
I thought making a link to the FAQ would be even better

**Comment by khanhtc1202** [comment]
Let's do both, with the FAQ link to the docs on the Managing Piped directory

**Comment by khanhtc1202** [comment]
@ouchi2501 Could you open a PR for this 😄

**Comment by ouchi2501** [comment]
@khanhtc1202 OK👌
I'll try to find time to make a PR.
