### ISSUE TITLE
Support group mentions for slack notification

### ISSUE THREAD

**Issue by minhquang4334** [pipe-cd/pipecd#4730]
**What would you like to be added**:
I think it would be better to support slack group mentions. 

**Why is this needed**:
If someone is assigned to and leaves the development team, it is difficult to change the PipeCD notification settings every time.

Currently [pipeCD is supporting individual user mention](https://pipecd.dev/docs-v0.45.x/user-guide/managing-piped/configuration-reference/#notificationreceiverslack), but the syntax for individual user mentions and group mentions is different in Slack. 
refs: https://api.slack.com/reference/surfaces/formatting#mentioning-groups

As a workaround, if I put the format <!subteam^ID> into mentionedAccounts, it gets displayed as <@@subteam_name> in the Mention To section of the Slack message, with double @@ and even angle brackets <>

**Comment by hungran** [comment]
@minhquang4334  i would like to work on this issue
