### ISSUE TITLE
Documentation of install command by asdf is wrong

### ISSUE THREAD

**Issue by BIwashi** [pipe-cd/pipecd#4755]
**What happened**:

[Command-line tool: pipectl | PipeCD](https://pipecd.dev/docs-v0.45.x/user-guide/command-line-tool/#asdfhttpsasdf-vmcom)
The pipectl install command by Asdf described in this document did not work.

**What you expected to happen**:

That I can successfully install pipectl by modifying the commands in the order of `asdf plugin add` in the documentation.

```diff
-asdf add plugin pipectl
+asdf plugin add pipectl
```

[Getting Started | asdf](https://asdf-vm.com/guide/getting-started.html#_4-install-a-plugin)
```console
asdf plugin add <name> [<git-url>]      Add a plugin from the plugin repo OR,
                                        add a Git repo as a plugin by
                                        specifying the name and repo url
```

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

**Comment by ffjlabo** [comment]
Thank you!
