### ISSUE TITLE
Out of Sync when we set false as the env for Cloud Run 

### ISSUE THREAD

**Issue by ffjlabo** [pipe-cd/pipecd#4783]
**What happened**:

Out of Sync when we set false as the env for Cloud Run. We need to investigate it.

<img width="460" alt="Cursor_と_PipeCD___Office_Hours📆_-_Google_ドキュメント" src="https://github.com/pipe-cd/pipecd/assets/40124947/2428aa77-dcb0-4121-9f47-6e788e19af88">

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

**Comment by t-kikuc** [comment]
@ffjlabo 
Is this PR the same as https://github.com/pipe-cd/pipecd/issues/4790?
If so, could you pleaes decide which one to close ?

**Comment by t-kikuc** [comment]
This issue seems duplicated https://github.com/pipe-cd/pipecd/issues/4783#issuecomment-1978469383

**Comment by ffjlabo** [comment]
Sorry I missed 🙏 Thanks
