### ISSUE TITLE
Plan Preview sometimes failed when connecting github.com with ssh

### ISSUE THREAD

**Issue by ffjlabo** [pipe-cd/pipecd#4794]
**What happened**:

![Slack_-_Threads_-_CyberAgent](https://github.com/pipe-cd/pipecd/assets/40124947/a5476454-f3ea-4e17-b319-ca869a22e693)

Plan Preview sometimes failed when connecting github.com with ssh like the img.

error message
```
exit status 128, out: ssh: Could not resolve hostname github.com: Try again fatal: Could not read from remote repository.
```

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

**Comment by ffjlabo** [comment]
Workaround: retry plan preview on GitHub

**Comment by khanhtc1202** [comment]
Close this due to retry plan preview can resolve this. Looks like it's a network issue 👍
