### ISSUE TITLE
Display the Base64 encoded value of the Piped Key when registering a new piped

### ISSUE THREAD

**Issue by ouchi2501** [pipe-cd/pipecd#4796]
**What would you like to be added**:
- as Title

I'm envisioning that it will be added below the following screen.
![image](https://pipecd.dev/images/quickstart-piped-registered.png)

The source code that needs to be modified is believed to be as follows.
https://github.com/pipe-cd/pipecd/blob/master/web/src/components/settings-page/piped/index.tsx

**Why is this needed**:

Currently, when adding a Piped configuration, the Piped ID and Piped Key are displayed. However, in reality, base64 encoding is required when specifying the piped config. Opening a terminal to manually base64 encode the Piped Key is cumbersome. Displaying the base64 encoded value below the Piped ID and Piped Key would streamline the process, enhancing the user experience.

refs:
- https://pipecd.dev/docs-v0.46.x/installation/install-piped/
- https://pipecd.dev/docs-v0.46.x/quickstart/

**Comment by dgannon991** [comment]
I would be interested in picking this up, I'll try and get it done over the holiday weekend :)
