### ISSUE TITLE
Show Application ID on the application page

### ISSUE THREAD

**Issue by ffjlabo** [pipe-cd/pipecd#4810]
**What would you like to be added**:

It would be nice to show an application ID with a copiable field on the application page.

![PipeCD](https://github.com/pipe-cd/pipecd/assets/40124947/5a92a4a4-8554-4b29-8907-58e0c2439580)

![Cursor_と_PipeCD](https://github.com/pipe-cd/pipecd/assets/40124947/9761d385-7484-4eb2-a3ae-1fcee548c521)

**Why is this needed**:

It is helpful to share the application ID for debugging.

**Comment by t-kikuc** [comment]
Nice issue!
Even though the ID is included in the URL, users don't know it is the ID.
<img width="491" alt="image" src="https://github.com/pipe-cd/pipecd/assets/97105818/8f30f105-4a30-486a-9714-56ad22ca2edd">

**Comment by dgannon991** [comment]
I'd like to work on this, as part of contribfest.

**Comment by ffjlabo** [comment]
Thank you! assigned to @dgannon991 👍
