### ISSUE TITLE
Show Deployment ID on the deployment page

### ISSUE THREAD

**Issue by ffjlabo** [pipe-cd/pipecd#4811]
**What would you like to be added**:

It would be nice to show a deployment ID with a copiable field on the deployment page.

<img width="1430" alt="PipeCD" src="https://github.com/pipe-cd/pipecd/assets/40124947/af89f335-03d7-4fa3-b6ec-66da5bdc5ad3">

copy button↓
![image](https://github.com/pipe-cd/pipecd/assets/40124947/d20956be-86fc-4169-ba28-00a90f9a6c02)

**Why is this needed**:

It is helpful to share the deployment ID for debugging.

> Even though the ID is included in the URL, users don't know it is the ID.

**Comment by dgannon991** [comment]
Hi @ffjlabo, is there a place you were hoping it would appear in the list of items? To get it going I'll add it to the top of the list like the application ID, but I'll wait to hear back before submitting :)

**Comment by ffjlabo** [comment]
@dgannon991 
> I'll add it to the top of the list like the application ID

Thank you for the confirmation! It's OK 👍

**Comment by ffjlabo** [comment]
@dgannon991
Hi David. The photos for the KubeCon EU are out, and there are also photos of the Contribute Fest :)
We can find them on the Flicker (from CNCF)↓
https://www.flickr.com/photos/143247548@N03/53613331318/

Thank you for coming and for your contribution. 👍

**Comment by dgannon991** [comment]
Hi @ffjlabo, oh amazing, thank you for the link :) There's definitely a lot to scroll through! I'll try and see if I made it into any of the contribfest ones :) 

Glad to have helped, it's always fun to get involved in a new project and see how other people do things 🤗
