### ISSUE TITLE
Support SCRIPT_RUN for ECSApp deployment

### ISSUE THREAD

**Issue by minhquang4334** [pipe-cd/pipecd#4813]
**What would you like to be added**:
Currently, PipeCD only supports SCRIPT_RUN for KubernetesApp deployments, but it would be nice to have SCRIPT_RUN support for ECSApp deployments as well

refs: https://pipecd.dev/docs-v0.46.x/user-guide/managing-application/customizing-deployment/script-run/

**Why is this needed**:
A more customized deployment of ECSApp is possible

**Comment by t-kikuc** [comment]
We can already use SCRIPT_RUN for ECSApp.
https://github.com/pipe-cd/pipecd/pull/5018
