### ISSUE TITLE
Could not resolve hostname github.com

### ISSUE THREAD

**Issue by ffjlabo** [pipe-cd/pipecd#4876]
**What happened**:

Sometimes there are flaky behaviors in the piped component (e.g. Plan Preview, launcher ).
We need to investigate the cause.

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

**Comment by ffjlabo** [comment]
ref: https://github.com/pipe-cd/pipecd/issues/4794

**Comment by t-kikuc** [comment]
seems a network issue. https://github.com/pipe-cd/pipecd/issues/4794
