### ISSUE TITLE
Way to install pipectl using homebrew

### ISSUE THREAD

**Issue by khanhtc1202** [pipe-cd/pipecd#4879]
**What would you like to be added**:

Currently, we can install pipectl using `asdf` and `aqua.` For developers, it would be great if we could install it using a "standard" package manager for macOS, like homebrew.

**Why is this needed**:

**Comment by peaceiris** [comment]
Can I work on this as my first contribution for PipeCD?

**Comment by peaceiris** [comment]
I have created my pull-request.

- https://github.com/pipe-cd/pipecd/pull/4880
