### ISSUE TITLE
[feat] Support OIDC for the SSO

### ISSUE THREAD

**Issue by t-kikuc** [pipe-cd/pipecd#4906]
**What would you like to be added**:

Support OIDC for Control Plane's SSO.

**Why is this needed**:

Currently, only GitHub and Google are supported for the SSO.
However, some users want to use the SSO with other general protocols(OIDC, OAuth, SAML, LDAP, ...), especially those who need to use their internal auth system.

**Comment by t-kikuc** [comment]
@kumo-rn5s will try this issue, thanks!

**Comment by kumo-rn5s** [comment]
@t-kikuc Thank you. 
I will open the PR this month.

**Comment by khanhtc1202** [comment]
@kumo-rn5s Thanks a lot for having interest 😄 Please ping us here if you need any help while implementing this 🤝

**Comment by kumo-rn5s** [comment]
The source code about this feature itself is complete, and I am currently conducting integration tests with the following provider. 
- Keycloak
- Cognito
However, debugging the control plane is taking longer than expected, and it seems unlikely that we will make it in time for v0.48.0.

By the way, if you have any efficient debugging methods for the control plane, please let me know. It would be helpful if there is a way to run the debug based on VSCode.
