### ISSUE TITLE
Failed to install PipeCD by pipectl as quickstart command missing

### ISSUE THREAD

**Issue by RainbowMango** [pipe-cd/pipecd#5129]
I'm trying to install PipeCD as per the [quickstart guide](https://pipecd.dev/docs/quickstart/), but unfortunately, I can't use `pipectl quickstart` command to start the installation process as there is no `quickstart` sub-command at all:

```
# pipectl quickstart --version v0.48.4
2024/08/12 20:36:58 unknown command "quickstart" for "piped"
```
I'm not sure if this document is outdated.

**Enviornments**
```
# pipectl version
Version: v0.48.4, GitCommit: eec680f1dfed2b016ee809e278ce498a046ba831, BuildDate: 20240802-042451
```

**Comment by RainbowMango** [comment]
@khanhtc1202 Could you please take a look?

**Comment by khanhtc1202** [comment]
Hi @RainbowMango 🙌 I just tested running the quickstart follow the docs instruction and it works as expected (see below stdout)
```shell
╰─ # OS="darwin" or "linux"
curl -Lo ./pipectl https://github.com/pipe-cd/pipecd/releases/download/v0.48.4/pipectl_v0.48.4_darwin_amd64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 18.5M  100 18.5M    0     0   479k      0  0:00:39  0:00:39 --:--:-- 1168k

╭─ ~/workspace/tests/pipecd-test ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ✔  took 40s  at 21:55:53 
╰─ chmod +x ./pipectl

╭─ ~/workspace/tests/pipecd-test ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ✔  at 21:55:57 
╰─ ./pipectl quickstart --version v0.48.4
Installing the controlplane in quickstart mode...
```

Please ensure that the command here is `pipectl` not `piped` or `pipecd`. Could you rerun it?

**Comment by RainbowMango** [comment]
Yeah, you are right!

Forgive me for my stupid mistake I mistakenly downloading the `piped` instead of `pipectl` from https://github.com/pipe-cd/pipecd/releases/tag/v0.48.4.

Now I installed it successfully and continue to experiment with the excellent features. 
Thank you very much.

**Comment by khanhtc1202** [comment]
Thank you 🙌
