### ISSUE TITLE
Enable restart policy property for ECS application

### ISSUE THREAD

**Issue by tom-256** [pipe-cd/pipecd#5144]
**What would you like to be added**:
update github.com/aws/aws-sdk-go-v2/service/ecs to v1.45.0 to set the restart policy in ECS task definitions.

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-restart-policy.html
https://github.com/aws/aws-sdk-go-v2/blob/release-2024-08-15/service/ecs/CHANGELOG.md#v1450-2024-08-15

**Why is this needed**:
To control the restarting of containers.

**Comment by t-kikuc** [comment]
Thank you.
As you said, updating the SDK version is enough to use `RestartPolicy`. We don't need to fix codes.

cf. 
https://github.com/pipe-cd/pipecd/blob/41c3f714d173c21e1a1c44b20510def4ef6bbffe/pkg/app/piped/platformprovider/ecs/client.go#L183
