### ISSUE TITLE
logpersister graceful shutdown

### ISSUE THREAD

**Issue by naonao2323** [pipe-cd/pipecd#5156]
**What would you like to be added**:
The `flushAll` method in the `logpersister` package should wait for all `flushFromLastCheckpoint` calls to complete before proceeding. Currently, it initiates these calls asynchronously using `go sp.flushFromLastCheckpoint(ctx)`, which may lead to the `cancel` being executed immediately, not allowing the expected persister.gracePeriod(30-second timeout) to function correctly. 

https://github.com/pipe-cd/pipecd/blob/master/pkg/app/piped/logpersister/persister.go#L159
**Why is this needed**:

**Comment by khanhtc1202** [comment]
Thanks for your interest. Can you submit a fix for this 👀
