### ISSUE TITLE
Cannot navigate to the edit page even after clicking "Edit this page".

### ISSUE THREAD

**Issue by Reimei1213** [pipe-cd/pipecd#5287]
**What happened**:
Clicking “Edit this page” in the upper right corner takes me to an [unintended page](https://github.com/pipe-cd/pipecd/edit/master/docs/content/en//docs-v0.49.x/user-guide/metrics).

- Extra slash between en and docs-v0.49.x in url
- Missing .md extension

![スクリーンショット 2024-10-22 23 27 47](https://github.com/user-attachments/assets/58a7878d-bf3f-4b20-ae20-b5126949309a)

**What you expected to happen**:

I wanted to transition to [this page](https://github.com/pipe-cd/pipecd/edit/master/docs/content/en/docs-v0.49.x/user-guide/metrics.md).

**How to reproduce it**:

https://pipecd.dev/docs-v0.49.x/user-guide/metrics/

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

**Comment by ntheanh201** [comment]
IMO, this happened because of this commit: https://github.com/pipe-cd/pipecd/pull/5017
When I ran Hugo locally with version 0.92.1, this issue didn't happen.
When I ran Hugo locally with version 0.128.0, this issue happened.

**Comment by khanhtc1202** [comment]
@ntheanh201 @Reimei1213 Thanks for noticing us.

Could you also check the "Edit this page" link on this page? ref: https://pipecd.dev/docs-v0.49.x/quickstart/

Looks like if the docs markdown file is `_index.md` under the path name, it could jump correctly. So, for whatever fix, please ensure it also works with this kind of link.
