### ISSUE TITLE
A potential risk in pipe-cd that could lead to takeover of the cluster

### ISSUE THREAD

**Issue by HouqiyuA** [pipe-cd/pipecd#5293]
Dear Team Members:

Greetings! Our team is very interested in your project and we recently identified a potential RBAC security risk while doing a security assessment of your project. Therefore, we would like to report it to you and provide you with the relevant details so that you can fix and improve it accordingly.

Details:

In this Kubernetes project, there is a ClusterRole that has high-risk risk permissions for arbitrary operating privileges for arbitrary resources. https://github.com/pipe-cd/pipecd/blob/master/quickstart/manifests/piped.yaml. It meand this ClusterRole has superuser privileges and can perform almost any operation in the cluster. If an attacker steals a service account with this privilege，he can elevate the privileges and further take over the entire cluster.

Please confirm the purpose of the assignment of this permission and consider using a more granular permission non-assignment rule.
Best wishes.

HouqiyuA

**Comment by t-kikuc** [comment]
Thank you for reporting, but security issues **MUST NOT BE PUBLIC**. See https://github.com/pipe-cd/pipecd/blob/master/CONTRIBUTING.md#security-bugs.

Besides, this is not a risk because users can choose a way that fits their policy.
