### ISSUE TITLE
Drift Detection Issue with ECS Apps

### ISSUE THREAD

**Issue by HoangNguyen689** [pipe-cd/pipecd#5336]
**What happened**:

After upgrading PipeCD to v0.49.3, all ECS applications in the PipeCD console are displayed as "Out Of Sync". 
The detected drift includes:
- Configuration settings that are not specified in the `servicedef.yaml` file.
- Environment variables that have not been changed but are still flagged as differences.

**What you expected to happen**:

- Unchanged environment variables should not be flagged as drift.
- Drift detection should only report differences for properties explicitly managed by `servicedef.yaml`
- Configuration settings not specified in `servicedef.yaml` should be ignored by the drift detection process.

**How to reproduce it**:

- Navigate to the PipeCD console and view any ECS application.
- Notice that all ECS applications are marked as "Out Of Sync".
- Inspect the detected diff to see unexpected changes.

**Environment**:
- `piped` version: v0.49.3
- `control-plane` version:
- Others:

**Potential Cause**

The issue is likely due to the incorrect handling of the order of environment variables.

**Caution Notes** (advised from @t-kikuc)
- service.DeploymentConfiguration: 
  - If `head` is nil, then `live` should also be set to nil. This is to prevent issues caused by unexpected default values. 
  - Add an item to the func comment. (Under `TODO: Maybe we should check diff of following fields`)
- environment
  - Make sure to sort both live and head environment variables. There’s a possibility that this behaviour might change in the future, so it’s important to handle this now.
  - It’s recommended that the sorting logic be extracted into a separate function, for example: `func sortKeyPairs(kps []types.KeyValuePair)`
  - When sorting, use slices.Clone() to create a copy of the Environment array before performing operations. This prevents modifications to the original array, which could otherwise cause issues in the PlanPreview process.

**Comment by t-kikuc** [comment]
Thank you for reporting. 

We should fix the `ignoreParameters()` func.

https://github.com/pipe-cd/pipecd/blob/920620e93ca55a6a400a12afe5cf998451516937/pkg/app/piped/driftdetector/ecs/detector.go#L240

> Configuration settings that are not specified in the servicedef.yaml file.

- Cause: ECS sets default values for `DeploymentConfiguration` if it is not specified in servicedef.yaml, 
- Solution: Ignore the diff of `DeploymentConfiguration` if it's not specified.

> Environment variables that have not been changed but are still flagged as differences.

- Cause: `ContainerDefinitions[].Environments` are sorted by ECS.
- Solution:  Sort the `Environments` in both headManifest and liveManifest
