### ISSUE TITLE
Support gradual rollout of an application to multiple clusters

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipecd#926]
**What would you like to be added**:

Currently, doing a progressive rollout of an application can be done by splitting that application into multiple smaller apps.
Each app will be handled by a `piped` running inside a cluster. But it would be more convenient if we could doing without splitting the app.

I created this issue for more discussion.

**Why is this needed**:

**Comment by nghialv** [comment]
We are thinking about adding "requires" feature to the application: while registering a new application you can specify one or more other applications as the required list. The application will be triggered only if its required ones were successfully deployed.

With PipeCD, multiple applications can refer to the same configuration directory in Git, using the same deployment configuration file. So the "requires" feature can be more flexible, it can be used not only for doing gradual rollout to multiple clusters but also doing application dependency.

**Comment by danmx** [comment]
Sounds good.
Other features that would be very useful are:
- deployment retries
- pre/post-hooks (like in Helm or ArgoCD; check if cluster is in "unavailable" state before deploying),
- (advanced) conditional dependencies (with e.g. webhooks to services e.g. Prometheus for metrics check):
  - after successful deployment I want to listen to some custom business metrics to make a decision to promote the deployment to the next cluster,
  - tolerate e.g. one failed deployment (while it's retrying)
  - skip cluster if it's "unavailable" and add it to the bottom of the queue

I'm wondering, from what you're saying if I would like to deploy N apps to M clusters, I'd have to have N*M application objects, right? I'd require a custom higher level object (Helm chart, CRD, etc.) to wrap it for better Developer Experience (same thing is happening currently for Apps of Apps for ArgoCD).

**Comment by nghialv** [comment]
@danmx Thank you for the informative comment.

> (advanced) conditional dependencies (with e.g. webhooks to services e.g. Prometheus for metrics check)

We are having `ANALYSIS` and `WAIT` and `WAIT_APPROVAL` stages so I think you can use them to customize your deployment.
https://pipecd.dev/docs/user-guide/adding-a-manual-approval/

>  I'd require a custom higher level object (Helm chart, CRD, etc.) to wrap it for better Developer Experience

You are absolutely right. To be honest, we were thinking about something like `Pipeline` (connecting multiple environments of the same app), or `Workflow` or yes maybe `Apps or App` as you said.

**Comment by nghialv** [comment]
We are planning to add a new feature for this use case and we called it as `Deployment Chain`.
A new RFC for this feature will be added soon.
